name: test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: pip

    - name: Lint with black
      run: |
        pip install black
        black --check src tests

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']
        install-typing-extensions: [false, true]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install package
      run: pip install .

    - name: Install test dependencies
      run: pip install -r tests/requirements.txt

    - name: Install typing-extensions
      if: ${{ matrix.install-typing-extensions == true }}
      run: pip install 'typing-extensions >= 4.8'

    - name: Test with pytest
      run: pytest -vvra
